models:
  LogisticRegression:
    solver: lbfgs
    max_iter: 1000
    penalty: l2
    C: 1.0
    random_state: 42

  RandomForest:
    n_estimators: 50
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

  XGBoost:
    n_estimators: 350
    max_depth: 20
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    eval_metric: logloss
    random_state: 42

  DecisionTree:
    max_depth: 6
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

  GradientBoosting:
    n_estimators: 50
    learning_rate: 0.1
    max_depth: 10
    random_state: 42




